#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SWGCreateData
@end

@interface SWGCreateData : SWGObject

/* 新建的打卡Id [optional]
 */
@property(nonatomic) NSString* _id;
/* 对应的任务Id [optional]
 */
@property(nonatomic) NSString* taskId;
/* 对应的BuildingId [optional]
 */
@property(nonatomic) NSString* buildingId;
/* 签名 [optional]
 */
@property(nonatomic) NSString* signature;
/* 数值 [optional]
 */
@property(nonatomic) NSString* quantity;
/* 是否放弃. [optional]
 */
@property(nonatomic) NSString* giveUpFlag;
/* 放弃理由 [optional]
 */
@property(nonatomic) NSString* giveUpReason;
/* 今日所有打卡的打卡时间, 以\",\"分隔 [optional]
 */
@property(nonatomic) NSString* checkTime;
/* 打卡日期. [optional]
 */
@property(nonatomic) NSString* checkDate;
/* 打卡过后, 用户当日的表现, 1表示打了一部分卡, 2表示全部完成 [optional]
 */
@property(nonatomic) NSString* performance;
/* 打完卡后用户增加的积分. [optional]
 */
@property(nonatomic) NSString* pointAdded;

@end
