#import <Foundation/Foundation.h>
#import "SWGCreateDatas.h"
#import "SWGObject.h"
#import "SWGApiClient.h"


/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

@interface SWGJobApi: NSObject

@property(nonatomic, assign)SWGApiClient *apiClient;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient;
-(void) addHeader:(NSString*)value forKey:(NSString*)key;
-(unsigned long) requestQueueSize;
+(SWGJobApi*) apiWithHeader:(NSString*)headerValue key:(NSString*)key;
///
///
/// 获取用户当前所有未暂停的Task, 并给出在一段时间内用户打过卡的所有日期
/// 获取用户当前所有未暂停的Task, 并给出在一段时间内用户打过卡的所有日期.
///
/// @param jobId 打卡Id
/// @param taskId 对应任务Id
/// @param picNum 图片数量
/// @param giveUpFlag 是否是放弃打卡, 1为是 0为不是
/// @param checkTime 本地打卡时间
/// @param onlineFlag 此次打卡是否在联网状态下记录, 1为是 0为不是
/// @param clientLocalTime 客户端当前时间
/// @param currentGiveUpFlag 当前卡是否处于放弃打卡状态, 1为是, 0为不是
/// @param signature 打卡签名
/// @param quantity 打卡数值
/// @param giveUpReason 放弃打卡理由
/// 
///
/// @return SWGCreateDatas*
-(NSNumber*) jobCreatePostWithCompletionBlock :(NSString*) jobId 
     taskId:(NSString*) taskId 
     picNum:(NSString*) picNum 
     giveUpFlag:(NSString*) giveUpFlag 
     checkTime:(NSString*) checkTime 
     onlineFlag:(NSString*) onlineFlag 
     clientLocalTime:(NSString*) clientLocalTime 
     currentGiveUpFlag:(NSString*) currentGiveUpFlag 
     signature:(NSString*) signature 
     quantity:(NSString*) quantity 
     giveUpReason:(NSString*) giveUpReason 
    
    completionHandler: (void (^)(SWGCreateDatas* output, NSError* error))completionBlock;
    



@end
