#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SWGPerformance
@end

@interface SWGPerformance : SWGObject

/* 当日表现, 0表示没有任何打卡,1表示打了一部分卡, 2表示全部完成. [optional]
 */
@property(nonatomic) NSNumber* performance;
/* 记录的日期. [optional]
 */
@property(nonatomic) NSString* recordDate;

@end
