#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SWGTaskData.h"


@protocol SWGTaskDatas
@end

@interface SWGTaskDatas : SWGObject

/* 错误信息. [optional]
 */
@property(nonatomic) NSString* statusCode;

@property(nonatomic) NSArray<SWGTaskData>* message;

@end
