#import <Foundation/Foundation.h>
#import "SWGTaskDatas.h"
#import "SWGPerformances.h"
#import "SWGObject.h"
#import "SWGApiClient.h"


/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

@interface SWGTaskApi: NSObject

@property(nonatomic, assign)SWGApiClient *apiClient;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient;
-(void) addHeader:(NSString*)value forKey:(NSString*)key;
-(unsigned long) requestQueueSize;
+(SWGTaskApi*) apiWithHeader:(NSString*)headerValue key:(NSString*)key;
///
///
/// 获取用户当前所有未暂停的Task, 并给出在一段时间内用户打过卡的所有日期
/// 获取用户当前所有未暂停的Task, 并给出在一段时间内用户打过卡的所有日期.
///
/// @param userId 用户Id
/// @param beginDate 开始日期, 格式为YYYY-MM-DD
/// @param endDate 结束日期, 格式为YYYY-MM-DD
/// 
///
/// @return SWGTaskDatas*
-(NSNumber*) taskGetByDateGetWithCompletionBlock :(NSString*) userId 
     beginDate:(NSString*) beginDate 
     endDate:(NSString*) endDate 
    
    completionHandler: (void (^)(SWGTaskDatas* output, NSError* error))completionBlock;
    


///
///
/// 查询用户在一个时间段内的任务执行状况
/// 查询用户在一个时间段内的任务执行状况.
///
/// @param userId 用户Id
/// @param beginDate 开始日期, 格式为YYYY-MM-DD
/// @param endDate 结束日期, 格式为YYYY-MM-DD
/// 
///
/// @return SWGPerformances*
-(NSNumber*) taskGetPerformanceGetWithCompletionBlock :(NSString*) userId 
     beginDate:(NSString*) beginDate 
     endDate:(NSString*) endDate 
    
    completionHandler: (void (^)(SWGPerformances* output, NSError* error))completionBlock;
    



@end
