#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SWGTaskData
@end

@interface SWGTaskData : SWGObject

/* Task的主键Id [optional]
 */
@property(nonatomic) NSString* taskId;
/* 记录的日期. [optional]
 */
@property(nonatomic) NSString* giveUpFlag;
/* 打卡说明 [optional]
 */
@property(nonatomic) NSString* _description;
/* Task标题 [optional]
 */
@property(nonatomic) NSString* title;
/* 累计打卡天数. [optional]
 */
@property(nonatomic) NSString* totalDateCount;
/* 累计打卡次数 [optional]
 */
@property(nonatomic) NSString* totalCheckCount;
/* 颜色. [optional]
 */
@property(nonatomic) NSString* color;
/* 是否置顶, 1为置顶, 0为不是. [optional]
 */
@property(nonatomic) NSString* stickFlag;
/* 所有打过卡的日期. [optional]
 */
@property(nonatomic) NSString* allDate;
/* 当前连续打卡天数. [optional]
 */
@property(nonatomic) NSString* currentStreak;
/* 当日最后两次打卡的时间,若jobCount为2则用\",\"分隔, 若jobCount为0或大于2则为null. [optional]
 */
@property(nonatomic) NSString* checkTime;
/* 当日打卡次数. [optional]
 */
@property(nonatomic) NSString* jobCount;
/* task的创建时间. [optional]
 */
@property(nonatomic) NSString* cTime;
/* 置顶时间. [optional]
 */
@property(nonatomic) NSString* stickTime;
/* 等级 [optional]
 */
@property(nonatomic) NSString* level;
/* 是否限时, 1为限时, 0为不限时. [optional]
 */
@property(nonatomic) NSString* timeLimitFlag;
/* 上次打卡数值, 若上次打卡没有记录数值或者没有打卡记录则返回null. [optional]
 */
@property(nonatomic) NSString* lastQuantity;
/* 提醒时间, 格式为HH:MM, 若不提醒则为-1. [optional]
 */
@property(nonatomic) NSString* alertTime;
/* 此卡是否隐私, 1为隐私, 0为不隐私. [optional]
 */
@property(nonatomic) NSString* privateFlag;
/* 卡积分. [optional]
 */
@property(nonatomic) NSString* point;
/* 是否自动分享, 1为是, 0为不是. [optional]
 */
@property(nonatomic) NSString* autoShareFlag;
/* 限时开始时间, 格式为HH:MM [optional]
 */
@property(nonatomic) NSString* beginTime;
/* 限时结束时间, 格式为HH:MM. [optional]
 */
@property(nonatomic) NSString* endTime;

@end
