FROM ruby:2.5

MAINTAINER CocoaPods

LABEL "com.github.actions.name"="Incremental Update"
LABEL "com.github.actions.description"="Adds a commit for CDN changes to a Specs Repo"
LABEL "com.github.actions.icon"="zap"
LABEL "com.github.actions.color"="blue"

RUN ls
CMD ["ls"]
